version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.7
  install:
    - pipfile: .
      path: .
      skip_lock: true
      dev: true
    - method: setuptools
      path: .
